language: c
env:
  - BRANCH=master

before_install:
  - export PATH="nim-$BRANCH/bin/nim/bin:${PATH:+:$PATH}"
  - export LD_LIBRARY_PATH=./htslib/
  - export PATH="nim-$BRANCH/bin${PATH:+:$PATH}"
  - export PATH="$(pwd)/nimble/src:$PATH"

install:
  - bash ./scripts/install.sh
script:
  - nimble test
  - bash functional-tests.sh
  - nim c -d:release --cc:$CC mosdepth.nim
  - ./mosdepth -h
cache:
  directories:
    - nim-master
    - nim-devel
branches:
  except:
    - gh-pages
